---

- name: ALERTMANAGER | Copy main server config
  template:
    src: 1_global_alertmanager.j2
    dest: "{{ alertmanager_conf_path }}/parts/1_global_alertmanager"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640

- name: ALERTMANAGER | Copy server config
  template:
    src: "{{ item }}"
    dest: "{{ alertmanager_conf_path }}/parts/{{ item | basename }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640
  with_fileglob:
    - "{{ alertmanager_config_templates_path }}/*.j2"

- name: ALERTMANAGER | Checking for parts...
  find:
    paths: "{{ alertmanager_conf_path }}/parts"
  register: check_parts

- name: ALERTMANAGER | Join config parts
  assemble:
    remote_src: true
    src: "{{ alertmanager_conf_path }}/parts"
    dest: "{{ alertmanager_conf_path }}/alertmanager.yml"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640
    delimiter: '\n'
  notify:
    - restart alertmanager

- name: ALERTMANAGER | Copy notification templates
  copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_notifications_templates_path }}/{{ item }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0640
  with_fileglob:
    - "{{ alertmanager_config_notifications_templates_path }}/*"
  notify:
    - reload alertmanager

- name: ALERTMANAGER | Copy logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/alertmanager
    mode: 0644
    owner: root
    group: root
  when: alertmanager_logrotate_enabled
