---

- name: ALERTMANAGER | Ensure alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    system: yes
    state: present

- name: ALERTMANAGER | Ensure alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    system: yes
    shell: "{{ alertmanager_user_shell }}"
    createhome: no

- name: ALERTMANAGER | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_user }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ alertmanager_root_path }}"
    - "{{ alertmanager_conf_path }}"
    - "{{ alertmanager_conf_path }}/parts"
    - "{{ alertmanager_notifications_templates_path }}"
    - "{{ alertmanager_bin_path }}"
    - "{{ alertmanager_log_path }}"

- name: ALERTMANAGER | Check alertmanager version
  command: alertmanager -version
  register: alertmanager_check
  changed_when: false
  ignore_errors: true

- name: ALERTMANAGER | Download package
  get_url:
    url: "{{ alertmanager_url }}"
    dest: "{{ alertmanager_download_path }}"
    mode: 0644
  when: alertmanager_force_reinstall or alertmanager_check is failed or "alertmanager, version {{ alertmanager_version }}" not in alertmanager_check.stderr

- name: ALERTMANAGER | Extract package
  unarchive:
    copy: no
    src: "{{ alertmanager_download_path }}/{{ alertmanager_package }}"
    dest: "{{ alertmanager_download_path }}"
  when: alertmanager_force_reinstall or alertmanager_check is failed or "alertmanager, version {{ alertmanager_version }}" not in alertmanager_check.stderr

- name: ALERTMANAGER | Copy binary
  copy:
    src: "{{ alertmanager_download_path }}/{{ alertmanager_release_name }}/alertmanager"
    dest: "{{ alertmanager_bin_path }}/alertmanager"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    remote_src: True
    mode: 0755
  when: alertmanager_force_reinstall or alertmanager_check is failed or "alertmanager, version {{ alertmanager_version }}" not in alertmanager_check.stderr
  notify: restart alertmanager

- name: ALERTMANAGER | Link binary
  file:
    src: "{{ alertmanager_bin_path }}/alertmanager"
    dest: "/usr/bin/alertmanager"
    state: link

- name: ALERTMANAGER | Copy Daemon script
  template:
    src: alertmanager.service.j2
    dest: /lib/systemd/system/alertmanager.service
    mode: 0644
  notify: restart alertmanager
