---

- name: ALERTMANAGER | Install
  import_tasks: install.yml
  tags:
    - install

- name: ALERTMANAGER | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: ALERTMANAGER | Service
  import_tasks: service.yml
  tags:
    - service
