---

alertmanager_download_path: /usr/src

alertmanager_user: prometheus
alertmanager_group: prometheus

alertmanager_root_path: /opt/alertmanager
alertmanager_bin_path: "{{ alertmanager_root_path }}/bin"
alertmanager_conf_path: "/etc/alertmanager"
alertmanager_templates_path: "{{ alertmanager_conf_path }}/conf.d"
alertmanager_data_path: "{{ alertmanager_root_path }}/data"
alertmanager_log_path: "/var/log/alertmanager"

alertmanager_port: 9093
